#!/bin/bash

checkDependencies() {
    dependencies=("dialog" "sshpass")

    for dep in "${dependencies[@]}"; do
        if [ ! "$(command -v "$dep")" ]; then
            fatal "[ERROR] Command $dep not installed."
        fi
    done

    if [ $EUID != 0 ]; then
        fatal "[ERROR] Sudo privileges required."
    fi
}

checkVariables() {
    variables=("routerIP" "routerUser" "routerPass")
    variables+=("$@")

    for var in "${variables[@]}"; do
        if [ -z "${!var}" ]; then
            fatal "[ERROR] Variable $var not set."
        fi
    done
}

fatal() {
    echo "$@" >&2
    kill -10 $proc
}

remoteExec() {
    sshpass -p "$routerPass" ssh "$routerUser"@"$routerIP" <<-EOF
	$1
	EOF
}

proc=$$
routerIP=
routerUser=
routerPass=
jellyfinIP=
playstation5IP=

trap 'exit 1' SIGUSR1

checkDependencies

while true; do
    menu=$(dialog --clear \
        --title "MEO FiberGateway Port Forwarding" \
        --menu "Select one of the following actions:" \
        0 0 0  \
        1 "Show Rules" \
        2 "Add Rule: Jellyfin" \
        3 "Remove Rule: Jellyfin" \
        4 "Add Rule: PS5 Remote Play" \
        5 "Remove Rule: PS5 Remote Play" \
        6 "Exit" \
        2>&1 >"$(tty)")

    clear

    case $menu in
        1)  
            checkVariables 
            remoteExec "/nat/virtual-servers/show"
            ;;
        2)
            checkVariables "jellyfinIP"
            remoteExec "/nat/virtual-servers/create --server-name=Jellyfin --server-ip=$jellyfinIP --protocol=TCP --ext-port-start=8096 --int-port-start=8096 --wan-intf=erouter0"
            ;;
        3)
            checkVariables "jellyfinIP"
            remoteExec "/nat/virtual-servers/remove --server-ip=$jellyfinIP --protocol=TCP --ext-port-start=8096 --int-port-start=8096"
            ;;
        4)
            checkVariables "playstation5IP"
            remoteExec "/nat/virtual-servers/create --server-name=PlayStation5 --server-ip=$playstation5IP --protocol=UDP --ext-port-start=9302 --int-port-start=9302 --wan-intf=erouter0\n/nat/virtual-servers/create --server-name=PlayStation5 --server-ip=$playstation5IP --protocol=TCP --ext-port-start=9295 --int-port-start=9295 --wan-intf=erouter0\n/nat/virtual-servers/create --server-name=PlayStation5 --server-ip=$playstation5IP --protocol=UDP --ext-port-start=9295 --ext-port-end=9297 --int-port-start=9295 --int-port-end=9297 --wan-intf=erouter0"
            ;;
        5)
            checkVariables "playstation5IP"
            remoteExec "/nat/virtual-servers/remove --server-ip=$playstation5IP --protocol=UDP --ext-port-start=9302 --int-port-start=9302\n/nat/virtual-servers/remove --server-ip=$playstation5IP --protocol=TCP --ext-port-start=9295 --int-port-start=9295\n/nat/virtual-servers/remove --server-ip=$playstation5IP --protocol=UDP --ext-port-start=9295 --ext-port-end=9297 --int-port-start=9295 --int-port-end=9297"
            ;;
        6)
            exit
            ;;
        *)
            exit
            ;;
    esac
done
